### ISSUE TITLE
Unable to build/start network-explorer

### ISSUE THREAD

**Issue by tckb** [streamr-dev/network-explorer#58]
hi folks, I tried to install/build the explorer. Looks to be like a missing dependency. 
FYI - 

```bash
[network-explorer] npm ci                                                                                                                                                                                   master
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@streamr/quick-dijkstra-wasm/-/quick-dijkstra-wasm-1.1.4.tgz
npm ERR! 404
npm ERR! 404  '@streamr/quick-dijkstra-wasm@1.1.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**Comment by hpihkala** [comment]
@tckb Hi! Looks like the repo and npm package were accidentally left private, but should be fixed now. Please note that the network explorer is still WIP. It's scheduled to be released together with the Brubeck milestone of the Streamr Network later this year, so in the wild it may not "do" much just yet. :)

**Comment by tckb** [comment]
@hpihkala  thanks! I was looking around to see how it does work from dev side of things. :) will check and update

**Comment by mondoreale** [comment]
Current `master` branch should build nicely. Let's close this.
